/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.akhir;

/**
 *
 * @author Angga
 */

import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;

public class FrontApp extends javax.swing.JFrame {

    /**
     * Creates new form FrontApp
     */
    public FrontApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lJudul = new javax.swing.JLabel();
        lPendaftaran = new javax.swing.JLabel();
        jNama = new javax.swing.JLabel();
        jNoid = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputNoid = new javax.swing.JTextField();
        ketNoid = new javax.swing.JLabel();
        bDaftar = new javax.swing.JButton();
        lJudul1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lJudul.setForeground(new java.awt.Color(255, 255, 255));
        lJudul.setText("SELAMAT DATANG DI RUMAH PRAKTEK");
        getContentPane().add(lJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        lPendaftaran.setForeground(new java.awt.Color(255, 255, 255));
        lPendaftaran.setText("Pendaftaran :");
        getContentPane().add(lPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jNama.setForeground(new java.awt.Color(255, 255, 255));
        jNama.setText("Nama :");
        getContentPane().add(jNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jNoid.setForeground(new java.awt.Color(255, 255, 255));
        jNoid.setText("No. ID:");
        getContentPane().add(jNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 200, -1));
        getContentPane().add(inputNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 200, -1));

        ketNoid.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ketNoid.setForeground(new java.awt.Color(255, 255, 255));
        ketNoid.setText("*No. ID dapat menggunakan BPJS, Kartu Member, KTP dsb.");
        getContentPane().add(ketNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        bDaftar.setText("Masuk");
        bDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(bDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, -1));

        lJudul1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lJudul1.setForeground(new java.awt.Color(255, 255, 255));
        lJudul1.setText("DR. STRANGE");
        getContentPane().add(lJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Teknik Komputer 2019\\2. TUGAS\\Praktikum DKP\\Untitled-1.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 911, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDaftarActionPerformed
        // TODO add your handling code here:
        String nama = inputNama.getText();
        String noId = inputNoid.getText();

        if(inputNama.getText().isEmpty() || inputNoid.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Masukkan Nama dan No.ID.");
        }
        else
        {
            MainApp objMain = new MainApp();
            objMain.getNama.setText(nama);
            objMain.getNoid.setText(noId);
            objMain.setVisible(true);
        }
    }//GEN-LAST:event_bDaftarActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDaftar;
    public static javax.swing.JTextField inputNama;
    public static javax.swing.JTextField inputNoid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNama;
    private javax.swing.JLabel jNoid;
    private javax.swing.JLabel ketNoid;
    private javax.swing.JLabel lJudul;
    private javax.swing.JLabel lJudul1;
    private javax.swing.JLabel lPendaftaran;
    // End of variables declaration//GEN-END:variables
}
