/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.akhir;

/**
 *
 * @author Angga
 */

import java.util.*;
import javax.swing.*;
import java.text.*;
import javax.swing.table.DefaultTableModel;

public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNama = new javax.swing.JLabel();
        colon = new javax.swing.JLabel();
        lbNoid = new javax.swing.JLabel();
        colon1 = new javax.swing.JLabel();
        getNama = new javax.swing.JTextField();
        getNoid = new javax.swing.JTextField();
        lbAlamat = new javax.swing.JLabel();
        colon2 = new javax.swing.JLabel();
        lbJeniskelamin = new javax.swing.JLabel();
        colon3 = new javax.swing.JLabel();
        inputAlamat = new javax.swing.JTextField();
        cbJeniskelamin = new javax.swing.JComboBox<>();
        lbKeluhan = new javax.swing.JLabel();
        colon4 = new javax.swing.JLabel();
        lbIsidata = new javax.swing.JLabel();
        lbTanggal = new javax.swing.JLabel();
        colon5 = new javax.swing.JLabel();
        cbTgl = new javax.swing.JComboBox<>();
        slash = new javax.swing.JLabel();
        cbBln = new javax.swing.JComboBox<>();
        slash1 = new javax.swing.JLabel();
        bDaftar = new javax.swing.JButton();
        lbJampraktek = new javax.swing.JLabel();
        colon6 = new javax.swing.JLabel();
        tahun = new javax.swing.JLabel();
        inputKeluhan = new javax.swing.JTextField();
        cbJampraktek = new javax.swing.JComboBox<>();
        wib = new javax.swing.JLabel();
        bHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePasien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        colon8 = new javax.swing.JLabel();
        lbAntrian = new javax.swing.JLabel();
        ketTabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNama.setForeground(new java.awt.Color(255, 255, 255));
        lbNama.setText("Nama");
        getContentPane().add(lbNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 86, -1, -1));

        colon.setForeground(new java.awt.Color(255, 255, 255));
        colon.setText(":");
        getContentPane().add(colon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 86, -1, -1));

        lbNoid.setForeground(new java.awt.Color(255, 255, 255));
        lbNoid.setText("No. ID");
        getContentPane().add(lbNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 124, -1, -1));

        colon1.setForeground(new java.awt.Color(255, 255, 255));
        colon1.setText(":");
        getContentPane().add(colon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 121, -1, -1));

        getNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNamaActionPerformed(evt);
            }
        });
        getContentPane().add(getNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 83, 230, -1));

        getNoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNoidActionPerformed(evt);
            }
        });
        getContentPane().add(getNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 118, 230, -1));

        lbAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lbAlamat.setText("Alamat");
        getContentPane().add(lbAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 156, -1, -1));

        colon2.setForeground(new java.awt.Color(255, 255, 255));
        colon2.setText(":");
        getContentPane().add(colon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 156, -1, -1));

        lbJeniskelamin.setForeground(new java.awt.Color(255, 255, 255));
        lbJeniskelamin.setText("Jenis Kelamin");
        getContentPane().add(lbJeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 191, -1, -1));

        colon3.setForeground(new java.awt.Color(255, 255, 255));
        colon3.setText(":");
        getContentPane().add(colon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 191, -1, -1));
        getContentPane().add(inputAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 153, 230, -1));

        cbJeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Pria", "Wanita", "Belum Diketahui" }));
        getContentPane().add(cbJeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 188, -1, -1));

        lbKeluhan.setForeground(new java.awt.Color(255, 255, 255));
        lbKeluhan.setText("Keluhan");
        getContentPane().add(lbKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 226, -1, -1));

        colon4.setForeground(new java.awt.Color(255, 255, 255));
        colon4.setText(":");
        getContentPane().add(colon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 226, -1, -1));

        lbIsidata.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbIsidata.setForeground(new java.awt.Color(255, 255, 255));
        lbIsidata.setText("Isi Kelengkapan Data :");
        getContentPane().add(lbIsidata, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        lbTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbTanggal.setText("Tanggal");
        getContentPane().add(lbTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 261, -1, -1));

        colon5.setForeground(new java.awt.Color(255, 255, 255));
        colon5.setText(":");
        getContentPane().add(colon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 261, -1, -1));

        cbTgl.setMaximumRowCount(31);
        cbTgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 258, -1, -1));

        slash.setForeground(new java.awt.Color(255, 255, 255));
        slash.setText("/");
        getContentPane().add(slash, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 261, -1, -1));

        cbBln.setMaximumRowCount(12);
        cbBln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cbBln, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 258, -1, -1));

        slash1.setForeground(new java.awt.Color(255, 255, 255));
        slash1.setText("/");
        getContentPane().add(slash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 261, -1, -1));

        bDaftar.setText("Daftar");
        bDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(bDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 335, -1, -1));

        lbJampraktek.setForeground(new java.awt.Color(255, 255, 255));
        lbJampraktek.setText("Jam Praktek");
        getContentPane().add(lbJampraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 296, -1, -1));

        colon6.setForeground(new java.awt.Color(255, 255, 255));
        colon6.setText(":");
        getContentPane().add(colon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 296, -1, -1));

        tahun.setForeground(new java.awt.Color(255, 255, 255));
        tahun.setText("2020");
        getContentPane().add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 261, -1, -1));
        getContentPane().add(inputKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 223, 230, -1));

        cbJampraktek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "10.00-12.00", "14.00-16.00", "18.00-20.00" }));
        getContentPane().add(cbJampraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 293, -1, -1));

        wib.setForeground(new java.awt.Color(255, 255, 255));
        wib.setText("WIB");
        getContentPane().add(wib, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 296, -1, -1));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 335, -1, -1));

        tablePasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor", "Nama", "No. ID", "Alamat", "Jenis Kelamin", "Keluhan", "Tanggal", "Bulan", "Jam Praktek"
            }
        ));
        tablePasien.setOpaque(false);
        tablePasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 16, 859, 326));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Antrian");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 54, -1, -1));

        colon8.setForeground(new java.awt.Color(255, 255, 255));
        colon8.setText(":");
        getContentPane().add(colon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 54, -1, -1));

        lbAntrian.setForeground(new java.awt.Color(255, 255, 255));
        lbAntrian.setText("1");
        getContentPane().add(lbAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 54, -1, -1));

        ketTabel.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ketTabel.setForeground(new java.awt.Color(255, 255, 255));
        ketTabel.setText("*klik baris pada tabel untuk mengeprint struk antrian");
        getContentPane().add(ketTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 351, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Teknik Komputer 2019\\2. TUGAS\\Praktikum DKP\\Untitled-2.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNamaActionPerformed

    private void getNoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNoidActionPerformed

    private void bDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDaftarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tbl= (DefaultTableModel)tablePasien.getModel();
        
        if(getNama.getText().isEmpty() || getNoid.getText().isEmpty() || inputAlamat.getText().isEmpty() || inputKeluhan.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Mohon masukkan semua data.");
        }
//        else if(getNama.getText().equals(tbl.getValueAt(0,1).toString()))
//        {
//            JOptionPane.showMessageDialog(null, "Data sudah terdaftar.");
//        }
        else
        {
            String data[] = {lbAntrian.getText(),
            getNama.getText(),
            getNoid.getText(),
            inputAlamat.getText(),
            (String)cbJeniskelamin.getSelectedItem(),
            inputKeluhan.getText(),
            (String)cbTgl.getSelectedItem(),
            (String)cbBln.getSelectedItem(),
            (String)cbJampraktek.getSelectedItem()};
            
            tbl.addRow(data);
            
            int noAntrian = Integer.parseInt(lbAntrian.getText());
            noAntrian++;
                
            String antrian = String.valueOf(noAntrian);
            lbAntrian.setText(antrian);
        
            String reset = "";
            String resetCb1 = "--";
            String resetCb2 = "1";
            
            getNama.setText(reset);
            getNoid.setText(reset);
            inputAlamat.setText(reset);
            cbJeniskelamin.setSelectedItem(resetCb1);
            inputKeluhan.setText(reset);
            cbTgl.setSelectedItem(resetCb2);
            cbBln.setSelectedItem(resetCb2);
            cbJampraktek.setSelectedItem(resetCb1);
            }
        
    }//GEN-LAST:event_bDaftarActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        String reset = "";
        String resetCb1 = "--";
        String resetCb2 = "1";
        
        getNama.setText(reset);
        getNoid.setText(reset);
        inputAlamat.setText(reset);
        cbJeniskelamin.setSelectedItem(resetCb1);
        inputKeluhan.setText(reset);
        cbTgl.setSelectedItem(resetCb2);
        cbBln.setSelectedItem(resetCb2);
        cbJampraktek.setSelectedItem(resetCb1);
    }//GEN-LAST:event_bHapusActionPerformed

    private void tablePasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel tbl= (DefaultTableModel)tablePasien.getModel();
//        int antrianPasien = tablePasien.getSelectedRow();
//        
//        lbAntrian.setText(tbl.getValueAt(antrianPasien, 0).toString());
//        getNama.setText(tbl.getValueAt(antrianPasien, 1).toString());
//        getNoid.setText(tbl.getValueAt(antrianPasien, 2).toString());
//        inputAlamat.setText(tbl.getValueAt(antrianPasien, 3).toString());
//        cbJeniskelamin.setSelectedItem(tbl.getValueAt(antrianPasien, 4).toString());
//        inputKeluhan.setText(tbl.getValueAt(antrianPasien, 5).toString());
//        cbTgl.setSelectedItem(tbl.getValueAt(antrianPasien, 6).toString());
//        cbBln.setSelectedItem(tbl.getValueAt(antrianPasien, 7).toString());
//        cbJampraktek.setSelectedItem(tbl.getValueAt(antrianPasien, 8).toString());
//        

        PrintApp objPrint = new PrintApp();
        
        DefaultTableModel tbl= (DefaultTableModel)tablePasien.getModel();
        int antrianPasien = tablePasien.getSelectedRow();
        
        objPrint.printAntrian.setText(tbl.getValueAt(antrianPasien, 0).toString());
        objPrint.printNama.setText(tbl.getValueAt(antrianPasien, 1).toString());
        objPrint.printNoid.setText(tbl.getValueAt(antrianPasien, 2).toString());
        objPrint.printAlamat.setText(tbl.getValueAt(antrianPasien, 3).toString());
        objPrint.printJk.setText(tbl.getValueAt(antrianPasien, 4).toString());
        objPrint.printKeluhan.setText(tbl.getValueAt(antrianPasien, 5).toString());
        objPrint.printTgl.setText(tbl.getValueAt(antrianPasien, 6).toString());
        objPrint.printBln.setText(tbl.getValueAt(antrianPasien, 7).toString());
        objPrint.printJam.setText(tbl.getValueAt(antrianPasien, 8).toString());
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        PrintApp.realTime.setText(sdf.format(date));
        
        objPrint.setVisible(true);
    }//GEN-LAST:event_tablePasienMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDaftar;
    private javax.swing.JButton bHapus;
    public static javax.swing.JComboBox<String> cbBln;
    public static javax.swing.JComboBox<String> cbJampraktek;
    public static javax.swing.JComboBox<String> cbJeniskelamin;
    public static javax.swing.JComboBox<String> cbTgl;
    private javax.swing.JLabel colon;
    private javax.swing.JLabel colon1;
    private javax.swing.JLabel colon2;
    private javax.swing.JLabel colon3;
    private javax.swing.JLabel colon4;
    private javax.swing.JLabel colon5;
    private javax.swing.JLabel colon6;
    private javax.swing.JLabel colon8;
    public static javax.swing.JTextField getNama;
    public static javax.swing.JTextField getNoid;
    public static javax.swing.JTextField inputAlamat;
    public static javax.swing.JTextField inputKeluhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ketTabel;
    private javax.swing.JLabel lbAlamat;
    public static javax.swing.JLabel lbAntrian;
    private javax.swing.JLabel lbIsidata;
    private javax.swing.JLabel lbJampraktek;
    private javax.swing.JLabel lbJeniskelamin;
    private javax.swing.JLabel lbKeluhan;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNoid;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JLabel slash;
    private javax.swing.JLabel slash1;
    private javax.swing.JTable tablePasien;
    private javax.swing.JLabel tahun;
    private javax.swing.JLabel wib;
    // End of variables declaration//GEN-END:variables
}
