/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.akhir;

/**
 *
 * @author Angga
 */

import java.util.*;
import javax.swing.*;

public class PrintApp extends javax.swing.JFrame {

    /**
     * Creates new form PrintApp
     */
    public PrintApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printNama3 = new javax.swing.JLabel();
        printNama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTiket = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        printNoid = new javax.swing.JLabel();
        printAlamat = new javax.swing.JLabel();
        printKeluhan = new javax.swing.JLabel();
        printJk = new javax.swing.JLabel();
        printTgl = new javax.swing.JLabel();
        slash = new javax.swing.JLabel();
        slash1 = new javax.swing.JLabel();
        printBln = new javax.swing.JLabel();
        tahun = new javax.swing.JLabel();
        printJam = new javax.swing.JLabel();
        bKembali = new javax.swing.JButton();
        ketJam = new javax.swing.JLabel();
        realTime = new javax.swing.JLabel();
        printAntrian = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        printNama3.setText("-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printNama.setForeground(new java.awt.Color(255, 255, 255));
        printNama.setText("-");
        getContentPane().add(printNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 54, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 54, -1, -1));

        lbTiket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTiket.setForeground(new java.awt.Color(255, 255, 255));
        lbTiket.setText("Tiket Antrian No.");
        getContentPane().add(lbTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 83, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 112, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 141, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Keluhan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 199, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jam Praktek");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 228, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 141, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 112, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 83, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 54, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 199, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 228, -1, -1));

        printNoid.setForeground(new java.awt.Color(255, 255, 255));
        printNoid.setText("-");
        getContentPane().add(printNoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 83, -1, -1));

        printAlamat.setForeground(new java.awt.Color(255, 255, 255));
        printAlamat.setText("-");
        getContentPane().add(printAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 112, -1, -1));

        printKeluhan.setForeground(new java.awt.Color(255, 255, 255));
        printKeluhan.setText("-");
        getContentPane().add(printKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 170, -1, -1));

        printJk.setForeground(new java.awt.Color(255, 255, 255));
        printJk.setText("-");
        getContentPane().add(printJk, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 141, -1, -1));

        printTgl.setForeground(new java.awt.Color(255, 255, 255));
        printTgl.setText("-");
        getContentPane().add(printTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 199, -1, -1));

        slash.setForeground(new java.awt.Color(255, 255, 255));
        slash.setText("/");
        getContentPane().add(slash, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 199, -1, -1));

        slash1.setForeground(new java.awt.Color(255, 255, 255));
        slash1.setText("/");
        getContentPane().add(slash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 199, -1, -1));

        printBln.setForeground(new java.awt.Color(255, 255, 255));
        printBln.setText("-");
        getContentPane().add(printBln, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 199, -1, -1));

        tahun.setForeground(new java.awt.Color(255, 255, 255));
        tahun.setText("2020");
        getContentPane().add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 199, -1, -1));

        printJam.setForeground(new java.awt.Color(255, 255, 255));
        printJam.setText("-");
        getContentPane().add(printJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 228, -1, -1));

        bKembali.setText("Kembali");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(bKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 280, -1, -1));

        ketJam.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        ketJam.setForeground(new java.awt.Color(255, 255, 255));
        ketJam.setText("*tiket antrian dicetak pada jam");
        getContentPane().add(ketJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 257, -1, -1));

        realTime.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        realTime.setForeground(new java.awt.Color(255, 255, 255));
        realTime.setText("-");
        getContentPane().add(realTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 257, -1, -1));

        printAntrian.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        printAntrian.setForeground(new java.awt.Color(255, 255, 255));
        printAntrian.setText("-");
        getContentPane().add(printAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 16, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Teknik Komputer 2019\\2. TUGAS\\Praktikum DKP\\hitam.png")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_bKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ketJam;
    private javax.swing.JLabel lbTiket;
    public static javax.swing.JLabel printAlamat;
    public static javax.swing.JLabel printAntrian;
    public static javax.swing.JLabel printBln;
    public static javax.swing.JLabel printJam;
    public static javax.swing.JLabel printJk;
    public static javax.swing.JLabel printKeluhan;
    public static javax.swing.JLabel printNama;
    public static javax.swing.JLabel printNama3;
    public static javax.swing.JLabel printNoid;
    public static javax.swing.JLabel printTgl;
    public static javax.swing.JLabel realTime;
    public static javax.swing.JLabel slash;
    public static javax.swing.JLabel slash1;
    public static javax.swing.JLabel tahun;
    // End of variables declaration//GEN-END:variables
}
